import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Media Management","description":"How to manage files, images, PDFs, annotations, and health checks in Notely.","frontmatter":{"title":"Media Management","description":"How to manage files, images, PDFs, annotations, and health checks in Notely.","keywords":"media, assets, images, pdf, workspace health, annotations","category":"Workspace"},"headers":[],"relativePath":"workspace/media.md","filePath":"workspace/media.md","lastUpdated":1783855203000}');
const _sfc_main = { name: "workspace/media.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="media" tabindex="-1">Media <a class="header-anchor" href="#media" aria-label="Permalink to &quot;Media&quot;">​</a></h1><p>Notely includes an integrated asset library for linking, viewing, and managing media files inside your notes.</p><h2 id="_1-asset-storage" tabindex="-1">1. Asset Storage <a class="header-anchor" href="#_1-asset-storage" aria-label="Permalink to &quot;1. Asset Storage&quot;">​</a></h2><p>All inserted files (images, PDFs, documents) are stored inside the <code>assets/</code> subfolder in your workspace. Markdown links refer to them relatively:</p><div class="language-markdown vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">![</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-light-text-decoration": "underline", "--shiki-dark": "#DBEDFF", "--shiki-dark-text-decoration": "underline" })}">My Image</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">](</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-light-text-decoration": "underline", "--shiki-dark": "#E1E4E8", "--shiki-dark-text-decoration": "underline" })}">./assets/image.png</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><hr><h2 id="_2-image-tools-annotation" tabindex="-1">2. Image Tools &amp; Annotation <a class="header-anchor" href="#_2-image-tools-annotation" aria-label="Permalink to &quot;2. Image Tools &amp; Annotation&quot;">​</a></h2><p>When viewing a note in Preview mode, hover over an image or right-click to access tools:</p><ul><li><strong>Crop</strong>: Recut and trim the image in-app.</li><li><strong>Annotate</strong>: Draw callout lines, arrows, highlights, and text notes on top of the image.</li><li><strong>Original Restore</strong>: Notely stores a backup of the original asset before your first edit, letting you revert changes later.</li></ul><hr><h2 id="_3-workspace-health-checks" tabindex="-1">3. Workspace Health Checks <a class="header-anchor" href="#_3-workspace-health-checks" aria-label="Permalink to &quot;3. Workspace Health Checks&quot;">​</a></h2><p>Keep your assets tidy using the Media Health Dashboard:</p><ul><li><strong>Unused Media</strong>: Lists media files in <code>assets/</code> not referenced by any note. Offers bulk-deletion.</li><li><strong>Missing Assets</strong>: Displays links in notes pointing to files that do not exist.</li><li><strong>Duplicate Media</strong>: Highlights duplicate file contents to save storage.</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("workspace/media.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const media = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  media as default
};
